// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Platform Team",
            "url": "https://wxops.cloud"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/catalog/activity": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns recent portal-created PRs (scaffold, register, edit) from gitops-infra.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List catalog activity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PR state: open, closed, all (default: all)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns all catalog entities. Use ?kind= to filter by entity kind (case-insensitive). Use ?search= for full-text search across name, title, description, and tags. Use ?owner= to filter by owning team (strips \"group:\" prefix).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List catalog entities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by kind (Component, API, System, Group, Resource, User, Doc)",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Full-text search across name, title, description, and tags",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by owner team (e.g. rocket-team or group:rocket-team)",
                        "name": "owner",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "entities array",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new catalog entity. Returns 409 Conflict if it already exists.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Register a new catalog entity",
                "parameters": [
                    {
                        "description": "Entity to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/catalog.Entity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a single catalog entity by kind and name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get catalog entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind (Component, API, System, Group, Resource, User, Doc)",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog.Entity"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates a catalog entity. Commits via PR in production or writes to disk in dev mode.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Update catalog entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated entity",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/catalog.Entity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes a catalog entity. Only platform-team admins can delete.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Delete catalog entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/ci": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns recent Gitea Actions workflow runs for the entity's source repo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get CI status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/content": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the raw Markdown content for a Doc entity. Fetches from spec.contentUrl via the Gitea client or the local reader.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get document content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Must be Doc",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Markdown content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/darlane": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Set up Darlane for an environment overlay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind (must be Component)",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/deprecate": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Deprecate an entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/packages": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Reads go.mod, package.json, requirements.txt, pyproject.toml from the source repo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get package dependencies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/promostatus": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get promotion status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/promote": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Promote entity lifecycle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/releases": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns Gitea Releases and container images from the Package Registry.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get releases and container images",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/spec": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the raw OpenAPI/AsyncAPI spec for an API entity. Resolves from inline definition or an openapi-typed link URL.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get API spec",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind (usually API)",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Raw OpenAPI YAML or JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/catalog/entities/{kind}/{name}/versions": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the latest tag for each environment (dev/staging/production) from the entity's source repo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get per-environment versions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entity name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/scaffold/projects": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "parameters": [
                    {
                        "description": "Project scaffold request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scaffold.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/scaffold.CreateProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/scaffold/projects/{team}/{appName}/config": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the current XTenantApp configuration for a project.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scaffold"
                ],
                "summary": "Get project config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "App name",
                        "name": "appName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scaffold.XTenantApp"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the XTenantApp configuration. Creates a PR in Gitea mode.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scaffold"
                ],
                "summary": "Update project config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "App name",
                        "name": "appName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scaffold.UpdateConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/scaffold/repos": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a Gitea repo from a golden-path template, generates XTenantApp CR and catalog entities. Opens a PR to gitops-infra.\nReturns non-template repos for the given owner org.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "scaffold",
                    "scaffold"
                ],
                "summary": "List team repos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Org/team name",
                        "name": "owner",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/scaffold/secrets": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates or updates vault secrets at {team}/{appName}/env.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scaffold"
                ],
                "summary": "Write vault secrets for a project",
                "parameters": [
                    {
                        "description": "team, appName, envVars[]",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/scaffold/templates": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns scaffold templates — from the local filesystem (dev) or from the Gitea template repository (production).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scaffold"
                ],
                "summary": "List scaffold templates",
                "responses": {
                    "200": {
                        "description": "templates array",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/callback": {
            "get": {
                "description": "Exchanges the authorization code for tokens, validates the id_token, and writes an encrypted session cookie.",
                "tags": [
                    "auth"
                ],
                "summary": "OIDC callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF state token",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to dashboard",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "get": {
                "description": "Redirects the browser to the Pinniped Supervisor authorization endpoint to begin the PKCE flow.",
                "tags": [
                    "auth"
                ],
                "summary": "Start OIDC login",
                "responses": {
                    "302": {
                        "description": "Redirect to OIDC provider",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Clears the session cookie, effectively logging the user out.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign out",
                "responses": {
                    "200": {
                        "description": "message: logged out",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns sub, username, and group memberships from the session. Available on both /auth/me (unauthenticated, for Next.js SSR) and /api/v1/me (protected).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user identity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.userResponsePayload"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns 200 as long as the process is alive. Used by the Kubernetes liveness and startup probes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "status: ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns 200 when the server is ready to accept traffic. Kept separate from /healthz so probes can be tuned independently.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "status: ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "catalog.Entity": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "description": "backstage.io/v1alpha1 (standard kinds) | wxops.cloud/v1alpha1 (Doc)",
                    "type": "string"
                },
                "kind": {
                    "description": "Component | API | System | Group | Resource | User | Doc",
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/catalog.EntityMetadata"
                },
                "spec": {
                    "$ref": "#/definitions/catalog.EntitySpec"
                }
            }
        },
        "catalog.EntityLink": {
            "type": "object",
            "properties": {
                "icon": {
                    "description": "Icon is a hint to the frontend (docs | dashboard | api | runbook | alert).",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "catalog.EntityMetadata": {
            "type": "object",
            "properties": {
                "annotations": {
                    "description": "Annotations carry tool-specific metadata.\nExample: \"gitea/source-location\": \"platform/payments-service\"",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "labels": {
                    "description": "Labels are free-form key/value pairs for filtering.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog.EntityLink"
                    }
                },
                "name": {
                    "description": "Name is the unique identifier within the entity's kind and namespace.\nUsed in API paths: /catalog/entities/Component/payments-service",
                    "type": "string"
                },
                "namespace": {
                    "description": "defaults to \"default\"",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "catalog.EntitySpec": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "Author is the user ref who authored this document.\nFormat: \"user:alice\"",
                    "type": "string"
                },
                "children": {
                    "description": "Children lists sub-group refs.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "consumesApis": {
                    "description": "ConsumesApis lists API entity refs consumed by this component.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "contentUrl": {
                    "description": "ContentURL is the Gitea raw URL for the markdown source file.",
                    "type": "string"
                },
                "definition": {
                    "description": "── API ──────────────────────────────────────────────────────────────\nDefinition holds the raw API spec (OpenAPI YAML, AsyncAPI, etc.)\nTypically left empty here and fetched from the repo link instead.",
                    "type": "string"
                },
                "dependsOn": {
                    "description": "DependsOn lists component or resource refs this entity depends on.\nFormat: \"component:default/user-service\", \"resource:default/payments-db\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "docStatus": {
                    "description": "DocStatus is the review lifecycle: proposed | under-review | accepted | deprecated | superseded",
                    "type": "string"
                },
                "docType": {
                    "description": "── Doc ──────────────────────────────────────────────────────────────────\nDocType classifies the document: rfc | adr | runbook | documentation",
                    "type": "string"
                },
                "domain": {
                    "description": "── System ───────────────────────────────────────────────────────────",
                    "type": "string"
                },
                "draft": {
                    "description": "Draft marks a Doc as not yet published. Draft docs are only visible\nto members of the owner team. Set to false (or omit) to publish.",
                    "type": "boolean"
                },
                "email": {
                    "description": "Email is the user's contact address.",
                    "type": "string"
                },
                "lifecycle": {
                    "description": "Lifecycle is the maturity stage: experimental | production | deprecated",
                    "type": "string"
                },
                "memberOf": {
                    "description": "── User ─────────────────────────────────────────────────────────────────\nMemberOf lists group refs this user belongs to.\nFormat: \"group:rocket-team\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "members": {
                    "description": "Members lists user refs that belong to this group.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "owner": {
                    "description": "── Common across most kinds ─────────────────────────────────────────\nOwner is a group or user reference: \"group:platform-team\", \"user:alice\"",
                    "type": "string"
                },
                "parent": {
                    "description": "── Group ────────────────────────────────────────────────────────────\nParent is the parent group ref for nested org structures.",
                    "type": "string"
                },
                "providesApis": {
                    "description": "ProvidesApis lists API entity refs exposed by this component.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "relatedTo": {
                    "description": "RelatedTo lists component/resource/API refs that this document describes.\nFormat: \"component:default/payments-service\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "supersededBy": {
                    "description": "SupersededBy is a Doc entity ref that replaces this document (e.g. RFC → ADR).\nFormat: \"doc:default/adr-001-kafka\"",
                    "type": "string"
                },
                "system": {
                    "description": "System groups related components under a named system.",
                    "type": "string"
                },
                "type": {
                    "description": "── Component ────────────────────────────────────────────────────────\nType classifies the component: service | website | library | pipeline | documentation",
                    "type": "string"
                }
            }
        },
        "handlers.userResponsePayload": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sub": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "scaffold.AuthSpec": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "scaffold.CreateProjectRequest": {
            "type": "object",
            "required": [
                "appName",
                "team",
                "templateId"
            ],
            "properties": {
                "apiEnabled": {
                    "type": "boolean"
                },
                "apiType": {
                    "description": "openapi | asyncapi | grpc",
                    "type": "string"
                },
                "appFlavor": {
                    "description": "Step 3: XTenantApp configuration",
                    "type": "string"
                },
                "appName": {
                    "description": "Step 1: Repository",
                    "type": "string"
                },
                "certManager": {
                    "type": "boolean"
                },
                "containerPort": {
                    "type": "integer"
                },
                "databaseSecrets": {
                    "type": "boolean"
                },
                "dbExtensions": {
                    "description": "Database (XTenantDatabase) — only extensions are project-level.\nName, tier, environment, and cluster details are configured per-env via the Promote flow.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "envVars": {
                    "description": "Plain env vars (non-secret, go into XTenantApp spec.parameters.env)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.KeyValue"
                    }
                },
                "extraLabels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.KeyValue"
                    }
                },
                "ingressEnabled": {
                    "description": "Base config — env-agnostic settings that live in base/xtenant-app.yaml.",
                    "type": "boolean"
                },
                "livenessPath": {
                    "type": "string"
                },
                "metricsPath": {
                    "description": "e.g. /metrics",
                    "type": "string"
                },
                "monitoringEnabled": {
                    "type": "boolean"
                },
                "namespace": {
                    "type": "string"
                },
                "openapiPath": {
                    "description": "relative path or public URL to spec",
                    "type": "string"
                },
                "packageManager": {
                    "type": "string"
                },
                "podAnnotations": {
                    "description": "Pod annotations and extra labels",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.KeyValue"
                    }
                },
                "readinessPath": {
                    "type": "string"
                },
                "reloader": {
                    "description": "Platform feature toggles — these declare WHAT is enabled project-wide.\nHOW each feature is configured per environment is handled via the Promote flow.",
                    "type": "boolean"
                },
                "rolloutType": {
                    "type": "string"
                },
                "runtimeVersion": {
                    "description": "Runtime (from template.yaml runtime section)",
                    "type": "string"
                },
                "ssoAuth": {
                    "description": "CertIssuer intentionally absent — ClusterIssuer is set per-env in the Promote flow.",
                    "type": "boolean"
                },
                "systemName": {
                    "description": "Catalog — System is auto-created with name = appName",
                    "type": "string"
                },
                "team": {
                    "type": "string"
                },
                "templateId": {
                    "description": "Step 2: Template",
                    "type": "string"
                },
                "vaultSecrets": {
                    "type": "boolean"
                }
            }
        },
        "scaffold.CreateProjectResponse": {
            "type": "object",
            "properties": {
                "appName": {
                    "type": "string"
                },
                "repoUrl": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "team": {
                    "type": "string"
                }
            }
        },
        "scaffold.DarlaneSpec": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "containerPort": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "env": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.EnvVar"
                    }
                },
                "fileSync": {
                    "$ref": "#/definitions/scaffold.FileSyncSpec"
                },
                "headerRouting": {
                    "$ref": "#/definitions/scaffold.HeaderRoutingSpec"
                },
                "image": {
                    "type": "string"
                },
                "productionOverride": {
                    "type": "boolean"
                },
                "replicas": {
                    "type": "integer"
                },
                "resources": {
                    "$ref": "#/definitions/scaffold.ResourceSpec"
                },
                "stickySession": {
                    "$ref": "#/definitions/scaffold.StickySessionSpec"
                },
                "telemetryPort": {
                    "type": "integer"
                },
                "trafficWeight": {
                    "type": "integer"
                },
                "ttl": {
                    "type": "string"
                }
            }
        },
        "scaffold.EnvFromRef": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "scaffold.EnvFromSource": {
            "type": "object",
            "properties": {
                "configMapRef": {
                    "$ref": "#/definitions/scaffold.EnvFromRef"
                },
                "secretRef": {
                    "$ref": "#/definitions/scaffold.EnvFromRef"
                }
            }
        },
        "scaffold.EnvVar": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "scaffold.FileSyncSpec": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "initFromImage": {
                    "description": "InitFromImage seeds the writable volume from a container image before sync starts.\nWhen empty the volume starts blank (scratch). Set to false to explicitly opt out.",
                    "type": "string"
                },
                "mountPath": {
                    "type": "string"
                }
            }
        },
        "scaffold.HeaderRoutingSpec": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "header": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "scaffold.IngressSpec": {
            "type": "object",
            "properties": {
                "auth": {
                    "$ref": "#/definitions/scaffold.AuthSpec"
                },
                "className": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "host": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "pathType": {
                    "type": "string"
                },
                "tls": {
                    "$ref": "#/definitions/scaffold.TLSSpec"
                }
            }
        },
        "scaffold.KeyValue": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "scaffold.ProbeDetail": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "failureThreshold": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "periodSeconds": {
                    "type": "integer"
                }
            }
        },
        "scaffold.ProbesSpec": {
            "type": "object",
            "properties": {
                "liveness": {
                    "$ref": "#/definitions/scaffold.ProbeDetail"
                },
                "readiness": {
                    "$ref": "#/definitions/scaffold.ProbeDetail"
                },
                "startup": {
                    "$ref": "#/definitions/scaffold.ProbeDetail"
                }
            }
        },
        "scaffold.ReloaderSpec": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "scaffold.RepositorySpec": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "scaffold.ResourceMeta": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "scaffold.ResourceSpec": {
            "type": "object",
            "properties": {
                "limits": {
                    "$ref": "#/definitions/scaffold.ResourceValues"
                },
                "requests": {
                    "$ref": "#/definitions/scaffold.ResourceValues"
                }
            }
        },
        "scaffold.ResourceValues": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                }
            }
        },
        "scaffold.RollingUpdate": {
            "type": "object",
            "properties": {
                "maxSurge": {
                    "type": "string"
                },
                "maxUnavailable": {
                    "type": "string"
                }
            }
        },
        "scaffold.RolloutStrategy": {
            "type": "object",
            "properties": {
                "rollingUpdate": {
                    "$ref": "#/definitions/scaffold.RollingUpdate"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "scaffold.SecretRefToggle": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "secretName": {
                    "type": "string"
                }
            }
        },
        "scaffold.SecretsFromSpec": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/scaffold.SecretRefToggle"
                },
                "database": {
                    "$ref": "#/definitions/scaffold.SecretRefToggle"
                }
            }
        },
        "scaffold.ServiceSpec": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "port": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "scaffold.StickySessionSpec": {
            "type": "object",
            "properties": {
                "cookieName": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "sameSite": {
                    "type": "string"
                },
                "secure": {
                    "type": "boolean"
                }
            }
        },
        "scaffold.TLSSpec": {
            "type": "object",
            "properties": {
                "clusterIssuer": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "secretName": {
                    "type": "string"
                }
            }
        },
        "scaffold.UpdateConfigRequest": {
            "type": "object",
            "properties": {
                "appFlavor": {
                    "type": "string"
                },
                "certManager": {
                    "type": "boolean"
                },
                "containerPort": {
                    "type": "integer"
                },
                "databaseSecrets": {
                    "type": "boolean"
                },
                "envVars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.KeyValue"
                    }
                },
                "extraLabels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.KeyValue"
                    }
                },
                "ingressEnabled": {
                    "type": "boolean"
                },
                "livenessPath": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "podAnnotations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.KeyValue"
                    }
                },
                "readinessPath": {
                    "type": "string"
                },
                "reloader": {
                    "type": "boolean"
                },
                "rolloutType": {
                    "type": "string"
                },
                "ssoAuth": {
                    "description": "CertIssuer intentionally absent — ClusterIssuer is set per-env in the Promote flow.",
                    "type": "boolean"
                },
                "templateId": {
                    "type": "string"
                },
                "vaultSecrets": {
                    "type": "boolean"
                }
            }
        },
        "scaffold.XTenantApp": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/scaffold.ResourceMeta"
                },
                "spec": {
                    "$ref": "#/definitions/scaffold.XTenantAppSpec"
                }
            }
        },
        "scaffold.XTenantAppParams": {
            "type": "object",
            "properties": {
                "appFlavor": {
                    "type": "string"
                },
                "appName": {
                    "type": "string"
                },
                "containerPort": {
                    "type": "integer"
                },
                "darlane": {
                    "$ref": "#/definitions/scaffold.DarlaneSpec"
                },
                "env": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.EnvVar"
                    }
                },
                "envFrom": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scaffold.EnvFromSource"
                    }
                },
                "image": {
                    "type": "string"
                },
                "imagePullSecrets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ingress": {
                    "$ref": "#/definitions/scaffold.IngressSpec"
                },
                "namespace": {
                    "type": "string"
                },
                "podAnnotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "probes": {
                    "$ref": "#/definitions/scaffold.ProbesSpec"
                },
                "reloader": {
                    "$ref": "#/definitions/scaffold.ReloaderSpec"
                },
                "replicas": {
                    "type": "integer"
                },
                "repository": {
                    "$ref": "#/definitions/scaffold.RepositorySpec"
                },
                "resources": {
                    "$ref": "#/definitions/scaffold.ResourceSpec"
                },
                "rolloutStrategy": {
                    "$ref": "#/definitions/scaffold.RolloutStrategy"
                },
                "secretsFrom": {
                    "$ref": "#/definitions/scaffold.SecretsFromSpec"
                },
                "service": {
                    "$ref": "#/definitions/scaffold.ServiceSpec"
                },
                "templateId": {
                    "type": "string"
                }
            }
        },
        "scaffold.XTenantAppSpec": {
            "type": "object",
            "properties": {
                "parameters": {
                    "$ref": "#/definitions/scaffold.XTenantAppParams"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "Encrypted session cookie issued after OIDC login.",
            "type": "apiKey",
            "name": "wxops_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "WxOps Portal API",
	Description:      "Internal developer platform API — service catalog, Kubernetes cluster management, and OIDC authentication via Pinniped.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
