apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-api
  description: User identity and profile gRPC API
  links:
    - url: https://gitea.example.com/platform/user-service/src/branch/main/openapi.yaml
      title: OpenAPI Spec
      icon: api
spec:
  type: grpc
  lifecycle: experimental
  owner: group:platform-team
  system: identity
